In [3]:
import numpy as np

In [54]:
num_fields = 5

x = np.random.randint(1,5,size=(num_fields+1,3))
x[0] = 0

In [55]:
mirror = np.zeros([2*num_fields+1,3])
negative = x[1:][::-1]
#negative = negative[::-1]
mirror[:num_fields] = negative
mirror[num_fields:] = x

In [56]:
print(mirror.T)

print(x.T)

[[2. 2. 4. 3. 2. 0. 2. 3. 4. 2. 2.]
 [2. 1. 2. 2. 2. 0. 2. 2. 2. 1. 2.]
 [3. 4. 4. 2. 4. 0. 4. 2. 4. 4. 3.]]
[[0 2 3 4 2 2]
 [0 2 2 2 1 2]
 [0 4 2 4 4 3]]
